/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-tertiary-fixed": "#221b08",
        "secondary-fixed": "#ffdea5",
        "error-container": "#ffdad6",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "background": "#fcf9f8",
        "on-secondary-fixed-variant": "#5d4201",
        "on-tertiary": "#ffffff",
        "secondary": "#775a19",
        "secondary-fixed-dim": "#e9c176",
        "on-secondary-fixed": "#261900",
        "surface-container-highest": "#e5e2e1",
        "on-secondary-container": "#785a1a",
        "primary-fixed-dim": "#c8c6c5",
        "outline": "#747878",
        "inverse-on-surface": "#f3f0ef",
        "surface-variant": "#e5e2e1",
        "on-tertiary-fixed-variant": "#504630",
        "on-error-container": "#93000a",
        "secondary-container": "#fed488",
        "tertiary": "#000000",
        "tertiary-container": "#221b08",
        "primary-fixed": "#e4e2e1",
        "surface": "#fcf9f8",
        "on-primary-fixed": "#1b1c1c",
        "on-surface": "#1c1b1b",
        "surface-bright": "#fcf9f8",
        "on-tertiary-container": "#8f8269",
        "surface-container": "#f0eded",
        "primary-container": "#1b1c1c",
        "on-primary-fixed-variant": "#474746",
        "on-primary": "#ffffff",
        "surface-tint": "#5f5e5e",
        "error": "#ba1a1a",
        "inverse-primary": "#c8c6c5",
        "surface-container-low": "#f6f3f2",
        "surface-dim": "#dcd9d9",
        "on-error": "#ffffff",
        "on-surface-variant": "#444748",
        "on-primary-container": "#858383",
        "inverse-surface": "#313030",
        "tertiary-fixed-dim": "#d4c5a8",
        "tertiary-fixed": "#f1e1c3",
        "primary": "#000000",
        "outline-variant": "#c4c7c7",
        "on-background": "#1c1b1b",
        "surface-container-high": "#eae7e7"
      },
      fontFamily: {
        "headline": ["Noto Serif"],
        "body": ["Manrope"],
        "label": ["Manrope"]
      },
      borderRadius: {"DEFAULT": "0.25rem", "lg": "0.5rem", "xl": "0.75rem", "full": "9999px"},
    },
  },
  plugins: [],
}
